### ISSUE TITLE
Add build option to use C++ gflags as backend

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/gflags#6]
The pure Rust implementation is good as a default, but it would be amazing to also provide:

```toml
[dependencies]
gflags = { version = "0.N", features = ["interop"] }
```

in which everything looks and behaves the same at the Rust source code level but the implementation switches to exactly the one used by C++ gflags, so that flags defined in Rust are seen by a C++ main function and vice versa.

Unsure whether this is possible.
